### ISSUE TITLE
Types are ignored in tcp DeleteByQuery

### ISSUE THREAD

**Issue by b789** [sksamuel/elastic4s#942]
when DeleteByQuery is used with tpc client the doctype option is ignored, as result more record than expected may be deleted.

I think the problem is in the populate function of DeleteByQueryDefinitionExecutable in the  DeleteExecutable.scala file.

Maybe something like the following would resolve the issue:

if (d.indexesAndTypes.types.nonEmpty)
        builder.source().setTypes(d.indexesAndTypes.types: _*)

i tried to compile the code from the v.5.4.3 tag just doing 'sbt compile' as suggested in the readme of the project but several compilation so i don't know how to test it.

**Comment by sksamuel** [comment]
Fixed in 5.4.4

**Comment by b789** [comment]
Great !  May i ask why it doesn't compile locally ? there's some additional steps to be done or some configurations ? I'm quite confuse on how the whole thing work.

**Comment by sksamuel** [comment]
Are you checking out master or release/5.4,x
Master might not work as its a work in progress against the 6 alpha2 release.
release/5.4.x definitely works: https://travis-ci.org/sksamuel/elastic4s/builds/241360045

**Comment by b789** [comment]
i war using v.5.4.3 tag version that still doesn't compile while v.5.4.4 and release/5.4.x compile just fine. I don't know if i'm messing up something with git regarding v.5.4.3 anyhow is not a big deal.
